


* [阅记] 解忧杂货铺 - 来自上天的祈祷


[内含微量剧透]


解忧杂货铺有点像微小说集, 由几个治愈系小故事串联而成, 跨越时间和空间, 被大叔用脑洞联系在了一起.

这是我读到的东野圭吾的第4部作品, 可能因为第一部<嫌疑人x的献身>让人感到太震(meng)撼(bi), 所以后来看的几本带来的惊喜感没有那么强烈. 
这不是一部推理小说, 然而书中的角角落落都布满可疑的线索, 让人不得不在意. 当脑中充满混乱的线索, 毫无头绪时, 我不幸的迎来了看起来有点哲学意味的结局.
当时十分失落, 随后就关掉手机睡觉了. 但那些奇怪的线索似乎不甘心就这样被遗忘掉, 总是在脑中盘旋, 早上醒来后依旧满脑这个故事.
于是我在心里按照小说里的时间线粗略的梳理, 越想越乱, 这个故事里似乎充满了矛盾, 又没有明确的谜题. 圭吾大叔你是要闹哪样啊!

思前想后,感觉首先需要解决的问题有2个:
- 这个平行空间的设定到底是怎样的? 为什么在同一夜中, 过去与现在的时间跨度不同?
- 为什么浪矢可以预知自己的祭日?

由于智商低, 只好求助于纸笔. 我又从头翻阅小说梳理了一下时间线, 希望能得到一些启示:

** 时间线

*** 1968
 贵之母亲去世

*** 1969 
 皆月晓子去世

*** 1970
 孤独的浪矢开始解答孩子们的疑问,心情开始变好
 - 回答了询问怎样考100分的孩子, 百分小毛头

*** 1978
 贵之发现手表时间异常, 杂货铺内时间流逝变快

 浪矢回答了绿河的咨询

*** 1979
**** 1979.6
 浪矢看到报道:绿河在开车是因贫血昏迷并坠河, 死前救了副驾上1岁左右的女儿

 贵之听说父亲关店回家看望时,门锁着

 杂货铺关闭

 浪矢开始梦到自己的灵魂能看到几十年后杂货店中发生的事

**** 1979.9.13
 浪矢写了遗书, 明确知道自己会在9.13号这天去世

 浪矢搬回杂货店过了一夜, 并收到了来自未来的来信
 - 百分小毛头
 - 川边绿的女儿, 见证孤儿院火灾, 后成为歌手女的经济人
 - 保罗的感谢信
 - 一张白纸

**** 1979.11 
 月兔投出了咨询信, 2012年的小偷三人组收到并回了信

*** 1980

**** 1980.7
 鱼店音乐人写信咨询, 三人组回复

**** 1980.9.13 
 浪矢去世

**** 1980.10 
 迷途的小狗(晴美)写信咨询, 三人组回复

**** 1988.12.24
 丸光园发生火灾, 鱼店音乐人为了救人丧命. 

 这场火灾影响到本书中几乎所有人物.

*** 2012
 在约定的9月13日, 小偷三人组在0点左右抢劫了晴美, 抢到了她装有感谢信的手包. 2:30分到达杂货店, 在6:00离开, 期间为三个人解答过烦恼. 

 三人组在离开之前, 把一张白纸投入了门口信箱中, 并得到来自过去的浪矢的回复.

 三人组在偷来的手包中 发现了晴美写给他们的感谢信


** 反思

**** 第一个问题: 时间线
仔细梳理后, 不得不承认, 杂货铺中存在着两条不同的时间线, 而这两条线的关系看起来有点牵强...

第一条: 1979年9月13日0点-6点, 浪矢爷爷可以收到来自2012年9月13日0点-6点间的来信, 这也能解释为何三人组最后寄出的白纸可以被收到.

第二条: 2012年9月13日0点-6点, 三人组可以与1979年9月-1980年10月这一年左右的时间联通.

**** 第二个问题: 祭日
反复看小说与时间表, 只能找到这样的解释: 浪矢在得知绿川死后, 并生病住院的期间, 反复做着预知梦. 他在梦中得知33年后杂货铺会连通现在与过去, 并以为自己会在1979年9月13号这天去世, 所以留了信给贵之,并要求这一天晚上去杂货店中收信.

[这个解释我并不满意, 为什么浪矢爷爷可准确的在1年后(1980)的这一天去世? 为什么公告上写33周年祭日, 而不是实际的22周年?]

**** 没有用到的线索
- 红豆包: 在1978年贵之的家中出现过一次,浪矢把它放在了佛龛上. 1979年浪矢病中出现过一次,浪矢没有在意.

- 贵之的手表: 1978年左右这个手表开始出现变慢的现象, 本以为从此时开始, 贵之的家中(既杂货铺)时间流逝开始变得异常. 但最后贵之的孙子接手这块表时, 表依旧每小时慢5分钟, 所以这个线索大概是故布疑阵吧.

**** 关于晓子
晓子临终前说, "我会在天上为大家的幸福祈祷".

这里几乎所有人物都与孤儿院产生过联系, 他们最后都过得还不错(除了歌手), 不知扭曲时空的力量是不是晓子的杰作.
 
于是末章标题总结了这整本书: 来自上天的祈祷


** 最后
这本小说的主要目的是说故事, 并不是推理. 前面碎碎念了一大坨没用的推导, 也该说说故事本身了. 
5个小故事形态各异, 主人公们各自背负着无奈的命运, 最后都直接或间接的通过杂货铺得到启示, 走向了各自的人生之路. 

我在微信阅读读到的这本书(没办法最近它太火了, 天天在眼前晃), 这个app可以在书中看到其他人对字句的短评. 每个故事中都有人热情的评论, 大家都能找到各自的共鸣点.  
我自己则是在歌手妹子在舞台上唱起<重生>时泪蹦了, 完全沉浸在了鱼店歌手的挣扎中, 这就是大部分有梦想没天赋的普通人的命运吧.

好的文学作品可以让各种人得到启发, 这本小说做到了 ( 虽然更喜欢作者的推理 :p



最后, 但愿这些胡乱猜测没有过分歪曲圭吾大叔的本意 (￣.￣) 
